### ISSUE TITLE
Iskljuciti komentare na blogu

### ISSUE THREAD

**Issue by morrigan** [UBIKhr/web#10]
Trenutno je uključen Disqus, predlažem to maknuti skroz.

<img width="812" alt="Screenshot 2020-12-26 at 21 19 57" src="https://user-images.githubusercontent.com/4976604/103158647-28e01880-47c0-11eb-9c50-9645ce4098d8.png">

**Comment by Swader** [comment]
Komentare cemo preko foruma furati.
