### ISSUE TITLE
Stranice 404 sa engleskim jezikom

### ISSUE THREAD

**Issue by morrigan** [UBIKhr/web#11]
Npr`/en/members/` bi trebalo loadati members page sa engleskim prijevodom, ali ne radi niti jedna podstranica.

Izgleda da se content mora duplicirati. Potrebno:
1. U `site/content` dodati folder `croatian` i kopirati u njega sve iz `english`
2. U `config.toml` fajlu pod "Croatian language" postaviti `contentDir = "content/croatian"`

Ne mogu naći mogućnost da jedan fallbacka na drugog...

**Comment by morrigan** [comment]
@Swader neko pametnije rješenje?

**Comment by Swader** [comment]
Nema potrebe za tim sada, cro only. Multilang kasnije.

**Comment by morrigan** [comment]
> Nema potrebe za tim sada, cro only. Multilang kasnije.

Disableala engleski. Imamo sve već tamo za multilang samo se mora duplicirati `content` za svaki jezik, issue: https://github.com/gohugoio/hugo/issues/5612. S obzirom da dodajemo blog postove sada, ne da mi se paziti na to. Možda možemo neki symlink kasnije napraviti s obzirom da ćemo blog vjerojatno pisati na jednom jeziku najčešće.
