### ISSUE TITLE
Logo i favicon

### ISSUE THREAD

**Issue by Swader** [UBIKhr/web#3]
Favicon je još uvijek od theme-a, a logo ne odgovara tamnoj pozadini.

Prijedlog:

- favicon promijeniti u stilizirani U
- logo napraviti kopiju s jednostavnim color invertom za korištenje na tamnim elementima

**Comment by morrigan** [comment]
Dodan favicon. Maknula logo od dolje jer bit ce bolje s novim dizajnom, a nema potrebe da se duplicira s obzirom da se navbar s logotipom vec sticka.
