### ISSUE TITLE
Members page tabs

### ISSUE THREAD

**Issue by Swader** [UBIKhr/web#5]
Members page ima nefunkcionalni svi / UO tab selector. Predlazem maknuti buduci da nikada necemo imati javni full popis svih clanova.

![image](https://user-images.githubusercontent.com/1430603/103158318-aace4280-47bc-11eb-97c9-990f42caf783.png)

**Comment by morrigan** [comment]
Razmisljala sam da tu budu i foundational memberi cc @lukaskywalk

**Comment by lukaskywalk** [comment]
Da, ideja je da tu idu foundational memberi. Kao badge of houour

**Comment by morrigan** [comment]
Gasim ovo kao issue da ne pisem sad logiku neku napredniju da se to makne dok je samo 1 tip labela jer to ide preko nekog plugina. Svakako uskoro dodajemo foundationale.
