### ISSUE TITLE
CSS nestabilan na members page

### ISSUE THREAD

**Issue by Swader** [UBIKhr/web#7]
Nekad je u redu, nekad newsletter input prekriva members, nekad su members stacked jedni preko drugih.

![image](https://user-images.githubusercontent.com/1430603/103158432-19f86680-47be-11eb-8cea-b8d3a26e4392.png)

**Comment by Swader** [comment]
Vjerujem da zbog CSS animacije koja je potpuno nepotrebna, predlazem izbaciti.

**Comment by morrigan** [comment]
Ja sam se nadala da je cache, nisam sigurna vise...
Ovo se koristi za taj dio https://yiotis.net/filterizr/#/

**Comment by Swader** [comment]
Ok, budem pogledao kad uhvatim tren

**Comment by morrigan** [comment]
@Swader mozes provjeriti sad? Dosta nestabilno (nekad je ok, nekad nije) se ponasalo do sada pa probaj par puta u privateu tako da otvoris direktno members ili odes s pocetne na members.

**Comment by Swader** [comment]
All good
